/*----------------------------------------------------------------------------

File:                   Errmsg.h
Course:                 ICSG 891, Masters Project
Author:                 Randall W. Charlick
Project Supervisor:     Dr. Peter G. Anderson

Date Started:           April 16, 1992
Last Modified:          July 21, 1992

Description:            This file contains definitions for all general error
                        codes used throughout this project.  This file is
                        maintained and consistent with the ErrMsg procedure
                        of RENDER.C.

----------------------------------------------------------------------------*/


#define  m_STOP                5
#define  m_HELP                4
#define  m_COMMAND             2
#define  m_MENU                1
#define  m_VALID               0
#define  m_MIS_IMAGE          -22
#define  m_UNK_IMAGE          -23
#define  m_MIS_OPT            -24
#define  m_INV_OPT            -25
#define  m_EXT_DISP           -26
#define  m_EXT_HELP           -27
#define  m_INV_PARM           -28
#define  m_SYN_ERR            -29
#define  m_ERR_ALLOC          -30
#define  m_ERR_FIELD          -31
#define  m_ERR_AVAIL          -32
#define  m_EXT_STAT           -33
#define  m_ERR_FOPEN          -34
#define  m_ERR_SETDISP        -35
#define  m_ERR_SETMODE        -36
#define  m_ERR_INITM          -37
#define  m_ERR_TRACK          -38
#define  m_INV_MODE           -39
#define  m_INV_CONF           -40
#define  m_UNK_PCX            -41
#define  m_EXT_PCX            -42
#define  m_MIS_PCX            -43
#define  m_ERR_PCX            -44
#define  m_MIS_RED            -45
#define  m_INV_RED            -46
#define  m_ERR_SUP            -47
#define  m_MUTEX              -48
#define  m_BAD_ROOT           -49
#define  m_MIS_CFG            -50
#define  m_BAD_INTENS         -100
