/*----------------------------------------------------------------------------

File:                   Globals.h
Course:                 ICSG 891, Masters Project
Author:                 Randall W. Charlick
Project Supervisor:     Dr. Peter G. Anderson

Date Started:           April 8, 1992
Last Modified:          July 21, 1992

Description:            This is the global defintiions file containing
                        general definitions used throughout the project
                        except for the MENU.C file.

----------------------------------------------------------------------------*/



/*  Very general and commonly used definitions  */

#define  NONE                  0
#define  VALID                 0
#define  FALSE                 0
#define  TRUE                  1
#define  OFF                   0
#define  ON                    1


/*  Screen sizing and graphics constants  */

#define  V_RATIO               0.04
#define  V_EXT_RATIO           0.06
#define  MONO                  1
#define  SINGLE                1
#define  DUAL                  2
#define  X_ORIGIN              0
#define  Y_ORIGIN              0


/*  String allocation constants  */

#define  LARGE_STR             80
#define  MED_STR               40
#define  SMALL_STR             20
