/*----------------------------------------------------------------------------

File:                   Select.h
Course:                 ICSG 891, Masters Project
Author:                 Randall W. Charlick
Project Supervisor:     Dr. Peter G. Anderson

Date Started:           May 16, 1992
Last Modified:          August 13, 1992

Description:            This file contains the definitions and structures
                        for the source file SELECT.C.


----------------------------------------------------------------------------*/



/*  Valid method types  */

#define  ITERATIVE        0
#define  FIBSCAN          1
#define  FIBONACCI        2
#define  FATFIBSCAN       3
#define  FATFIB           4


/*  Fibonacci Constants  */

#define  FIB_STD          0
#define  FIB_MOD          1
#define  FATSIZE          3
#define  FIBSTART         12
#define  SM_FIB           595
#define  MID_FIB          1278
#define  LG_FIB           1873
#define  FIRST_RED        27201
#define  SECOND_RED       152692
#define  THIRD_RED        265519



/*  General definitions  */

#define  NO_MENU         -1
#define  LEFT            -1
#define  MID_PT           0.5
#define  RIGHT            1
#define  BORDER           1
